spring:
  application:
    name: MyAsset

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/myasset_db}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

codef:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  public-key: ${PUBLIC_KEY}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: 1800000    # 30분 (ms)
  refresh-token-expiry: 604800000 # 7일 (ms)

aws:
  s3:
    enabled: ${AWS_S3_ENABLED:false} # local에서는 false로 변경 바람
    bucket: ${AWS_S3_BUCKET}
    region: ${AWS_S3_REGION}